### ISSUE TITLE
js Uncaught TypeError: Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by klimovdm** [onokumus/metisMenu#100]
metisMenu and bootstrap 3 issue (google chrome):

to reproduce error
1) open 
http://mm.onokumus.com/
2) resize browser window to width less than 768px 
3) click to collapsed main menu button in  the top-right corner of the screen

Error message:
`
bootstrap.min.js:6 Uncaught TypeError: Cannot read property 'height' of undefined
  d.show @ bootstrap.min.js:6
  d.toggle @ bootstrap.min.js:6
  d @ bootstrap.min.js:6
  (anonymous function) @ bootstrap.min.js:6
  n.extend.each @ jquery.min.js:2
  n.fn.n.each @ jquery.min.js:2
  c @ bootstrap.min.js:6
  (anonymous function) @ bootstrap.min.js:6
  n.event.dispatch @ jquery.min.js:3
  r.handle @ jquery.min.js:3
`

This error only occurs in conjunction with the metisMenu on the page.
btw, there is no errors with metisMenu ~1.1.3

**Comment by onokumus** [comment]
interesting
