### ISSUE TITLE
about font-awesome

### ISSUE THREAD

**Issue by shihao316558512** [onokumus/metismenu#101]
> `<span class="sidebar-nav-item-icon fa fa-code-fork"></span>`

![your code](https://raw.githubusercontent.com/shihao316558512/bootstrap/gh-pages/image/screenshot/metisMenu_error.png)

> you should use
> `<span class="sidebar-nav-item-icon fa fa-code-fork fa-fw"></span>`

![right code](https://raw.githubusercontent.com/shihao316558512/bootstrap/gh-pages/image/screenshot/metisMenu_right.png)

> see detail  [font-awesome](http://fontawesome.io/examples/#fixed-width)

**Comment by diegozhu** [comment]
btw , who can close it ?
