### ISSUE TITLE
collapsable menu is not working with ng-repeat in angular js

### ISSUE THREAD

**Issue by syamalachalasani** [onokumus/metisMenu#104]
When click on the menu link, Its not going to collapse. If i remove ng-repeat its working normally.
 `<li ng-repeat="(key, menu) in menus">
 <a href="#">Test</a>
   <ul class="nav nav-second-level">
     <li>
          <a href="#">second Level</a>
  </ul>
</li>`

**Comment by kumaranpkvel** [comment]
collapsable menu is not working with ng-repeat in angular js not working properly it has not  collapse while clicking that my code is below



`<li ng-repeat="menu_items in menulist" ng-show="menu_items.isparent" id="toggle" class="prevent" ui-sref-active="active" >
        

        <a href="#"><i class="{{menu_items.MenuIcon}}" ></i> <span class="nav-label">{{menu_items.Name}}</span><span class="fa arrow"></span> </a>

        <ul  class="nav nav-second-level collapse" >
          <li ui-sref-active="active" ng-repeat="menus in menu_items.sub_menu" ><a ui-sref="{{menus.MenuURL}}"><i class="{{menus.MenuIcon}}"></i> {{menus.Name}}</a></li>
        </ul>
      </li>`

**Comment by kumaranpkvel** [comment]
<li ng-repeat="menu_items in menulist" ng-show="menu_items.isparent" id="toggle" class="prevent" ui-sref-active="active" >
        

        <a href="#"><i class="{{menu_items.MenuIcon}}" ></i> <span class="nav-label">{{menu_items.Name}}</span><span class="fa arrow"></span> </a>

        <ul  class="nav nav-second-level collapse" >
          <li ui-sref-active="active" ng-repeat="menus in menu_items.sub_menu" ><a ui-sref="{{menus.MenuURL}}"><i class="{{menus.MenuIcon}}"></i> {{menus.Name}}</a></li>
        </ul>
      </li>
