### ISSUE TITLE
MetisMenu is not supported by older browser versions

### ISSUE THREAD

**Issue by mattmant** [onokumus/metisMenu#112]
Using the ECMAScript 6 features (https://github.com/lukehoban/es6features, "Arrows", "Let") we lose compatibility with a lot of browser versions (http://caniuse.com/#feat=arrow-functions).

It breaks out on IE and all previous versions of Safari (desktop and iOS).

**Comment by Johann-S** [comment]
They use Babel to convert ES6 into ES5

**Comment by mattmant** [comment]
Thank you!

Maybe a good idea to report these informations (use of ECMAScript 6 and Babel to convert it) on the main page of the project.
