### ISSUE TITLE
Top Dx menu' always open

### ISSUE THREAD

**Issue by Testato** [onokumus/metisMenu#113]
http://45.62.248.52
on my website that use metisMenu, when the page is under 768px (cellphone simulation), the metisMenu is always opened. Also if you refresh the page the menu' remain opened.
And if you try to close it by a click, the menu' reopened itself for a second time.
Only if you click another time the menu' is closed.

Another problem is also that when click a menu' link, the page recalled is opened, but the menu' also remain opened.

**Comment by onokumus** [comment]
@Testato 
add `collapse` class to following element
```html
<div class="sidebar-nav navbar-collapse">
...
</div>
```

Example
```html
<div class="sidebar-nav navbar-collapse collapse">
...
</div>
```

See http://getbootstrap.com/components/#navbar

**Comment by Testato** [comment]
Thanks for the answer,
I'm not a web programmer, you mean that i must change this on all html file ?
Or on css file ?

**Comment by onokumus** [comment]
I think you created the website with meteor. You should apply the solutions I told on the source code.
