### ISSUE TITLE
sonlandırıcı veya güncelleyici bir metot bulunmuyor

### ISSUE THREAD

**Issue by ogazioglu** [onokumus/metisMenu#116]
hocam selam,

eline sağlık, uluslararası seviyede kullanılan bir bileşen geliştirmişsin, eline sağlık. biz de kullanacağız inşallah ama bir sorun var: menü sadece ilk koşullara göre init oluyor, yani mvc tarafında render edilen htmllerde düzgün ancak angular gibi frameworkler tarafından veya manuel olaral dom modifikasyonu yapıldığında, örneğin #22 deki önerilenleri yaptığımızda kod sapıtıyor. menünün domdaki değişikliklere göre yeniden refresh olmasını tetikletebileceğimiz bir metot ekleyebilir misin? veya menüyü unload edebileceğimiz bir metot eklersen unload edip tekrar load ettirebiliriz. gerçi bunu refresh metodunun içinde de çağırabilirsin.

**Comment by onokumus** [comment]
Merhaba

Ben kendim de başka bir projede şöyle kullanıyorum. Önce menüdeki tüm metismenu sınıflarını ve attribute'leri başlangıç haline döndürüyorum.

```js
  stopMetisMenu: function() {
    $('.metismenu').find('li').removeClass('active');
    $('.metismenu').find('a').attr('aria-expanded', false);
    $('.metismenu').find('ul.collapse').removeClass('in').attr('aria-expanded', false);
  }
```
Ajax çağrısından sonra tekrar aktifleştiriyorum.

```js
$.ajax({
  ....
}).done(function() {
  $( '.metismenu' ).metisMenu();
});
```
Fakat bu tam bir çözüm değil tabii kide. Aslında bu şekilde bir fonksiyonun eklenmesi de gerekli :)

**Comment by ogazioglu** [comment]
Merhaba,

Yazdığın örnek kod menüyü tamamen sıfırlıyor. Bu da refresh ederken açık
olan menülerin kapanmasına da neden oluyor. Refresh için bunlara
dokunmaması lazım. Sadece işlevsel özelliklerini sıfırlaması ve rebind
etmesi lazım.

Aslında en sıkıntılı olanı şu click.metisMenu event inin off yapılamaması.
Ben şu şekilde denedim ama nedense kaldıramadım:

var data = $element.data('mm');if (data) {
    $element.find('a').off('click.metisMenu');
    $element.removeData("mm");
}
$element.metisMenu();


Örneğin bir menü item var : "Accounts", bunun child i yok henüz ve buna
tıklayınca account arama sayfasına düşüyoruz. Buradan bir account a
tıkladığımızda accounts menü item artık parent konuma geçsin, altında içine
girdiğim account gelsin, onun da altında o account ile ilgili itemler
gelsin istiyorum. Yani

   - Accounts

iken, bir account a tıklandığında

   - Accounts
   - Account XXX
         - Configuration
         - Data
         - Vs

şekline dönsün istiyorum. Ama accounts a da tıklanabilir olmasını
istiyorum. Çünkü accounts a tıklandığında tekrar arama sayfasına dönüp
dinamik olarak eklenen itemların kalkmasını ve menünün ilk duruma dönmesini
istiyorum. Bu oluyor ancak clickler düzelmiyor. Child itemler bir kez
eklenip metisMenu() çağrılınca

this
      .$element
      .find('li')
      .has('ul')
      .children('a')
      .on('click.metisMenu', function(e) { ...

koduyla click event i, children ı toggle yap olarak bir kez atanmışsa, hep
öyle kalıyor. altındaki itemlar kaybolsa da bu menü tıklanamaz hale
geliyor. aslında menü item üzerinde link varsa ve altında da childları
varsa, tıkladığında hem menüyü açıp hem de link e gidebilir. Bu olursa
bayağı bir sorun çözülmüş oluyor. Ayrıca eğer child i olan bir item
üzerinde link varsa, bunun belki açılıp kapanamaz olmasını sağlamak veya
bunu opsiyonel olarak belirleyebilmek lazım.


Onur Gazioğlu

11 Kasım 2016 10:51 tarihinde Osman Nuri Okumuş <notifications@github.com>
yazdı:

**Comment by onokumus** [comment]
@ogazioglu 
***
Stop and destroy metisMenu:
```js
$('#menu').metisMenu('dispose');
```
***
Call metisMenu again:
```js
$('#menu').metisMenu();
```

**Comment by ogazioglu** [comment]
2.6.0 sürümünü indirip denedim ancak bug var:

`TypeError: this.dispose is not a function
    at HTMLUListElement.<anonymous> (http://192.168.5.1/Scripts/metisMenu.js?v=2.6.0:372:22)
    at Function.each (http://192.168.5.1/Scripts/jquery-2.2.0.min.js:2:2773)
    at n.fn.init.each (http://192.168.5.1/Scripts/jquery-2.2.0.min.js:2:845)
    at n.fn.init._jQueryInterface [as metisMenu] (http://192.168.5.1/Scripts/metisMenu.js?v=2.6.0:366:25)`

**Comment by onokumus** [comment]
@ogazioglu 
internet üzerinden bir örnek paylaşabilir misiniz?

**Comment by ogazioglu** [comment]
Aşağıdaki şekilde çağırıyorum: 

`
var data = $element.data("metisMenu");
if (data) $element.metisMenu("dispose");
$element.metisMenu(options);
`

Tarayıcı: Chrome 54.0.2840.99 m (64-bit)

**Comment by danielserafimovik** [comment]
@ogazioglu you need to initialize metis menu first before calling the dispose
strange but that is how it works
after a lot of researching, I found this solution
           $element.metisMenu();
            $element.metisMenu("dispose")

hope this will help you too

**Comment by ogazioglu** [comment]
It seems that 2.6.1 fixed the "this.dispose is not a function at HTMLUListElement" problem.
So, thanks and best regards!

**Comment by aligoren** [comment]
@onokumus Selamlar. Vue'da bu menüyü kullanıyorum. Açıkcası bundan daha iyisini bulmak çok zor. Elinize saglik.

Ancak sayfa ilk init olduğunda ya da init olduktan sonra örneğin yetkiye göre çalışılan bir yapıda, filterlanan menü verisinden dolayı menü sapıtıyor. Sizce bu sorunu nasıl çözebiliriz?

İlk aşamada şöyle bir çözüm ürettim ama.

```js
let menuInterval = setInterval(async () => {
      if (this.menuItems.length > 0) {
        clearInterval(menuInterval);
      } else {
        setTimeout(async () => {
          await this.prepareMenu();
          await this._menuItems();
        }, 400);
      }
    }, 400);
```

prepareMenu methodu şöyle bir yapıda;

```js
this.mm = new MetisMenu("#side-menu", {
          toggle: false
        });
```

_menuItems ise şöyle

```js
_menuItems() {
      this.mm.dispose();
      if (this.menuItems.length == 0) {
        let file = "";
        switch (this.info.paketAdi) {
          case "Demo Paket":
            file = "full-menu";
            break;
          case "Ücretsiz Paket":
            file = "ucretsiz-menu";
            break;
          case "Standart Paket":
            file = "standart-menu";
            break;
          case "Pro Paket":
            file = "full-menu";
            break;
          default:
            //file = "ucretsiz-menu";
            break;
        }

        if (file) {
          let menu = require(`./menuler/${file}`).default({
            yetki: this.personelYetki,
            info: this.info
          });

          this.menuItems = menu;
        }
      }

      this.mm.update();
    }
```

Nasıl bir öneriniz olabilir bu konuda?

**Comment by onokumus** [comment]
> @onokumus Selamlar. Vue'da bu menüyü kullanıyorum. Açıkcası bundan daha iyisini bulmak çok zor. Elinize saglik.
> 
> Ancak sayfa ilk init olduğunda ya da init olduktan sonra örneğin yetkiye göre çalışılan bir yapıda, filterlanan menü verisinden dolayı menü sapıtıyor. Sizce bu sorunu nasıl çözebiliriz?
> 
> İlk aşamada şöyle bir çözüm ürettim ama.
> 
> ```js
> let menuInterval = setInterval(async () => {
>       if (this.menuItems.length > 0) {
>         clearInterval(menuInterval);
>       } else {
>         setTimeout(async () => {
>           await this.prepareMenu();
>           await this._menuItems();
>         }, 400);
>       }
>     }, 400);
> ```
> 
> prepareMenu methodu şöyle bir yapıda;
> 
> ```js
> this.mm = new MetisMenu("#side-menu", {
>           toggle: false
>         });
> ```
> 
> _menuItems ise şöyle
> 
> ```js
> _menuItems() {
>       this.mm.dispose();
>       if (this.menuItems.length == 0) {
>         let file = "";
>         switch (this.info.paketAdi) {
>           case "Demo Paket":
>             file = "full-menu";
>             break;
>           case "Ücretsiz Paket":
>             file = "ucretsiz-menu";
>             break;
>           case "Standart Paket":
>             file = "standart-menu";
>             break;
>           case "Pro Paket":
>             file = "full-menu";
>             break;
>           default:
>             //file = "ucretsiz-menu";
>             break;
>         }
> 
>         if (file) {
>           let menu = require(`./menuler/${file}`).default({
>             yetki: this.personelYetki,
>             info: this.info
>           });
> 
>           this.menuItems = menu;
>         }
>       }
> 
>       this.mm.update();
>     }
> ```
> 
> Nasıl bir öneriniz olabilir bu konuda?

Vue ile hiç çalışmadım. İsterseniz bir de https://github.com/onokumus/metismenujs kullanarak deneyin. Bu versiyonda jQuery bağımlılığı da yok.
