### ISSUE TITLE
Mismached anonymous define() module

### ISSUE THREAD

**Issue by networkedbenny** [onokumus/metisMenu#117]
If this is loaded through RequireJS, there is an error in v2.6.0:
Error: Mismatched anonymous define() module

At a guess, there appears to be an "extra" amd block in the dist/metisMenu.js file here:
https://github.com/onokumus/metisMenu/commit/73d6715683d6d74ec38d6797c49584438caab09f#diff-c8ac2609f7f0dbeb8be96a24a8da4fefR23

**Comment by onokumus** [comment]
Hi @networkedbenny 

Will you try again and share the result?

**Comment by networkedbenny** [comment]
Yes, v2.6.1 works. Thanks very much.
