### ISSUE TITLE
Your events are not working

### ISSUE THREAD

**Issue by Legends** [onokumus/metismenu#118]
Are they actually implemented ?

**Comment by onokumus** [comment]
@Legends 
Could you give some more detail?

**Comment by Bruno2049** [comment]
Hi @onokumus 

I have the same problem, the events are not working.
Here is the code that I use:

`// MetisMenu
    $('#side-menu').metisMenu()
        .on('shown.metisMenu', function (event)
        {
            console.log('SideMenuOpen: true');
            localStorage.setItem('SideMenuOpen', true);
        })
        .on('hidden.metisMenu', function (event)
        {
            console.log('SideMenuOpen: false');
            localStorage.setItem('SideMenuOpen', false);
        });`

**Comment by ObertShen** [comment]
@Legends @Bruno2049 I have the same problem, but it works after using the latest version of the plugin.
P.S. 
I use 1.x before.
