### ISSUE TITLE
transitionEndEmulator method doesn't work

### ISSUE THREAD

**Issue by Maxsl** [onokumus/metismenu#129]
'this' is undefined in transitionEndEmulator method.

**Comment by onokumus** [comment]
@Maxsl 
Please give more detail?

**Comment by Maxsl** [comment]
@onokumus 
This problem will cause an invalid when the mini-sidemenu is switched.
---------------------------------
metismenu.js - v2.6.2   line #129
---------------------------------
You can try to print.
like this:
    console.log(this);

:)

**Comment by Maxsl** [comment]
thanks.

**Comment by chengxuzhang** [comment]
console.log(this) ; no thanks
