### ISSUE TITLE
mix level 1 and level 2 side menu,click on level 1 menu and expanded level 2 menu wont collapse

### ISSUE THREAD

**Issue by ibreathebsb** [onokumus/metismenu#132]
## Version  v2.0.2

hello , im using this plugin for my side menu,and use level 1 and level 2 menu together.
here is the problem : 

when i click on a level 2 menu,it expanded,but if i dont choose any  child of that menu and click right on another level 1 menu,it wont collapse

**Comment by onokumus** [comment]
@ibreathebsb 
Could you share some of your codes?

**Comment by chengxuzhang** [comment]
什么意思？不会崩溃？
