### ISSUE TITLE
metismenu bootstrap code

### ISSUE THREAD

**Issue by 719media** [onokumus/metismenu#153]
i just spent way too long debugging an issue I was having with metismenu.

It appears you have jquery method in your codebase, $.emulateTransitionEnd, which looks like it was lifted from bootstrap, perhaps version 3.3 or so. This same method exists in bootstrap 4, and has been slightly changed in the latest bootstrap 4 beta 3, which released a few days ago.

Anyway, your plugin is causing some issues because of the conflicting $.emulateTransitionEnd versions. I am able to work around this issue somewhat by loading the bootstrap later on in my build chain, so their version gets loaded last, but it still would be good to remove this issue entirely.

Is there any way you can just use a local copy of this function instead of extending jquery? I would think using a jquery function with the same name as such a popular library as bootstrap would be a good reason to switch.

Thank you for your time.

**Comment by xcartmods** [comment]
Confirmed, menus break with Bootstrap Beta 3.

**Comment by 719media** [comment]
I had a moment to write back about this. The main issue here is that bootstrap dropped support for IE 9, which removes the need for
https://github.com/onokumus/metismenu/blob/master/dist/metisMenu.js#L48-L53

and replaces
https://github.com/onokumus/metismenu/blob/master/dist/metisMenu.js#L73-L83
with
```
return {
  end: 'transitionend'
};
```

I'm not sure if you want metis menu to support IE 9, but if not, I would recommend making those changes. I would also recommend perhaps namespacing your `$.fn.emulateTransitionEnd` to something like `$.fn.mmEmulateTransitionEnd` (much like you've namespaced `TRANSITION_END: 'mmTransitionEnd'`) given that bootstrap is such a hugely popular library.

Thank you for your time

**Comment by 719media** [comment]
https://github.com/onokumus/metismenu/pull/154

**Comment by xcartmods** [comment]
Genuis!   all good now. Thank you.
