### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by HamedFathi** [onokumus/metismenu#163]
Is it possibe for you to release a version without jquery as dependency?

Nowadays developers use Aurelia, Vue, Angular for their projects and dont need jquery.

**Comment by onokumus** [comment]
@HamedFathi 
metismenu 3.0.0-alpha.0 released.
https://github.com/onokumus/metismenu/tree/v3

**Comment by HamedFathi** [comment]
@onokumus 
Thank you so much very very helpful for me.
looks great, I tested and it works :)
