### ISSUE TITLE
Version v3 not work in IE11

### ISSUE THREAD

**Issue by llutti** [onokumus/metismenu#171]
Version: 3.0.0-alpha.2  

When I open [the demo site of metisMenu](http://mm.onokumus.com/v3/mm-vertical.html) occurs the error. The menu is not collapse your levels.

The console of IE11 show this message: "The object does not support the property or method 'entries'"

![image](https://user-images.githubusercontent.com/24873687/42654428-f73a34cc-85ee-11e8-9baf-9c0517cd48a4.png)

Regards,

Lucaino

**Comment by onokumus** [comment]
@llutti 
Hi Lucaino,

Will you try now?

**Comment by llutti** [comment]
@onokumus 

Hi,

  I tried now and all worked very well.

  Congratulations for your great work and thanks for your help.

  I will download the new v3 beta version to use in my project.

Best Regards,

Luciano

**Comment by onokumus** [comment]
@llutti 
Please close this issue.
