### ISSUE TITLE
More levels

### ISSUE THREAD

**Issue by robov** [onokumus/metismenu#19]
Is there a way that I can add more levels to the menu,. I see only

Root
- level 1
  -- level 2
  --- level 3
  ---- level 4 (how can i do this?)

I would like to add a  level 4

Thanks again for amazing work

**Comment by brettwinters** [comment]
Hello

Thanks so much for the great work on the menu! 

I noticed that although we can add as many levels as we want, the control stops indenting after the 4th level. I tried to change the width as a solution, but the indenting seems hardcoded in...

Regards

Brett

**Comment by onokumus** [comment]
@brettwinters 
Which demo page are you talking about?

**Comment by brettwinters** [comment]
Hi Osman

I'm loading the menu dynamically from ASP.net codebehind with 5 levels not from a demo. But let me make an example for you today to replicate the behaviour

BR Brett

**Comment by brettwinters** [comment]
My code: 

<div class="sidebar-nav">
            <ul class="metismenu" id="menu">
                <li>
                    <a class="has-arrow" href="#" aria-expanded="false">Menu1</a>
                    <ul aria-expanded="false" class="collapse">
                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false">Item1.1</a>
                            <ul aria-expanded="false" class="collapse">
                                <li>
                                    <a class="has-arrow" href="#" aria-expanded="false">Item1.1.1</a>
                                    <ul aria-expanded="false" class="collapse">
                                        <li>
                                            <a class="has-arrow" href="#" aria-expanded="false">Item1.1.1.1</a>
                                            <ul aria-expanded="false" class="collapse">
                                                <li>
                                                    <a>Item1.1.1.1.1</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

I have also attached the rendered output: 
![image](https://cloud.githubusercontent.com/assets/26474006/24319760/4f6fd098-1160-11e7-948c-8bd7185763fd.png)

**Comment by onokumus** [comment]
@brettwinters 
There is no definition for padding or margin in "metisMenu.css" file. This view is caused by the padding or margin definitions in your stylesheet files.

**Comment by brettwinters** [comment]
thanks for the headsup, I found it in the CSS. 

For any other users who have this issue, please add lines (as many levels as you need) to the mm-vertical.css as follows: 

.sidebar-nav .metismenu ul ul ul a {
    padding: 10px 15px 10px 60px;
}

.sidebar-nav .metismenu ul ul ul ul a {
    padding: 10px 15px 10px 75px;
}

.sidebar-nav .metismenu ul ul ul ul ul a {
    padding: 10px 15px 10px 80px;
}

.sidebar-nav .metismenu ul ul ul ul ul ul a {
    padding: 10px 15px 10px 95px;
}

.sidebar-nav .metismenu ul ul ul ul ul ul ul a {
    padding: 10px 15px 10px 100px;
}
