### ISSUE TITLE
Dependency on bootstrap

### ISSUE THREAD

**Issue by Proghat** [onokumus/metismenu#23]
Why did you add dependency on bootstrap in version 1.1.2?

The problem is there are 2 version of bootstrap: [bootstrap](https://github.com/twbs/bootstrap) and [bootstrap-sass](https://github.com/twbs/bootstrap-sass). And now it's hard to use metisMenu with the second one because it require to install unnecessary bootstrap.

Can we do anything with this?

Thank you for your work on metisMenu :heart:!

**Comment by onokumus** [comment]
@Proghat 
@AndrewEastwood 
Can you tell me your test result? 
https://github.com/onokumus/metisMenu/tree/2.0.0

**Comment by Proghat** [comment]
It works for me. Thank you! :heart_eyes:

Waiting for release :).
