### ISSUE TITLE
Animations duplicate on Safari browser

### ISSUE THREAD

**Issue by rderharo** [onokumus/metismenu#35]
metisMenu works great on every browser I have tested it on, except for Safari. I have tested on both OS X Mavericks and Yosemite with the same outcome.

When clicking on a menu category, the expanding animation occurs twice in a row. After the first animation, it resets and does it a second time.

**Comment by onokumus** [comment]
@rderharo 
Which metisMenu version did you test?

**Comment by rderharo** [comment]
I'm currently using v1.1.1.

**Comment by onokumus** [comment]
@rderharo 
Can you test this version. https://github.com/onokumus/metisMenu/tree/2.0.0

**Comment by rderharo** [comment]
Can confirm the same thing happens in 2.0.0.

**Comment by rderharo** [comment]
I tried looking more into this and still cannot find a solution. If I go to your demo page with Safari, it works fine. But on my app, it doubles the expanding animation.

One additional thing I noticed is that the collapsing animation is skipped. It just hides with no animation at all.

It's an AngularJS app, which is the only thing I can think of that would be unique versus the demo. I updated the bootstrap and metisMenu libraries to the latest versions with no effect.

**Comment by davebream** [comment]
I have the same problem [here](http://mdch.e-kei.pl/meetly_front/)

**Comment by davebream** [comment]
I fixed the problem.
For me the cause was my custom css on the submenu unordered list tag:
`ul.submenu { transition: all 0.2s ease-in; }`
It added a redundant transition, which doubled the plugin's one.

**Comment by rderharo** [comment]
Hmm. I do not have any transitions on anything else on my app, but I will dig deeper into the other libraries that I use to see if there is a conflict. 

Having said that, why would it only impact Safari and no other browser?
