### ISSUE TITLE
sub menu toggle not work in right to left

### ISSUE THREAD

**Issue by RahimGashti** [onokumus/metisMenu#36]
hello
sub menu toggle not work in right to left

**Comment by onokumus** [comment]
@rahimttl 
right to left?

**Comment by RahimGashti** [comment]
what?
yes when i change layout for right to left language like persian, toggle not work

**Comment by onokumus** [comment]
@RahimGashti 
https://onokumus.makes.org/thimble/LTQzODU2NjY1Ng==/metismenu-rtl

**Comment by RahimGashti** [comment]
thank you for reply
i found metis menu from template , and on that metis not worked
every think work in above link, thanks
