### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by vmartinetti** [onokumus/metismenu#37]
How to disable a item of list? Disabling means preventing to expand the item. Adding the .disabled of bootstrap causes the visual effect but still can be expanded.

**Comment by onokumus** [comment]
@vmartinetti 
it isn't supported a "disabled" option.

**Comment by radoslavius** [comment]
Now it works like this
```html
<a href="#" class='disabled' aria-expanded="false" aria-disabled="true">Label</a>
```

**Comment by vmartinetti** [comment]
Thanks, i'll try it.

**Comment by chriswiggins** [comment]
@vmartinetti see my PR #78 for this functionality
