### ISSUE TITLE
Does not apply bootstrap theme

### ISSUE THREAD

**Issue by mewsoft** [onokumus/metisMenu#38]
It does not apply Bootstrap themes. If it does not apply bootstrap themes so what makes it a bootstrap menu.

**Comment by onokumus** [comment]
@mewsoft 
it isn't a Bootstrap menu. it is a menu plugin and it does work with Bootstrap

**Comment by mewsoft** [comment]
No, your title says:

# Easy menu jQuery plugin for Twitter Bootstrap 3

**Comment by onokumus** [comment]
@mewsoft 
What do you recommend?

**Comment by mewsoft** [comment]
Just remove the word bootstrap 3 from your title, to be a jquery plugin is excellent, bootstrap itself is just little plugins for jquery.
