### ISSUE TITLE
Plugin not work 

### ISSUE THREAD

**Issue by skiokko** [onokumus/metisMenu#48]
Hi,
This plugin is great, but not work at all.
Not work your demos: if i extract all zip folder and lunch /test/ files like hover.html, metisFolder.html and others. All CSS is broken and no js functionality. 
![2015-05-24_145213](https://cloud.githubusercontent.com/assets/12584277/7787912/85ee5128-0224-11e5-9599-083237ffe7ca.jpg)

If i try to use in my website (with bootstrap 100% included and work good). same results...

Why this happen? in true seem a your error in create download package.
Thanks

**Comment by onokumus** [comment]
@skiokko 
This test folder doesn't work with pages viewed via the file:// protocol (like when opening a local HTML file). Because no all assets in the test folder. Execute the following command.
```bash
grunt serve
```

**Comment by skiokko** [comment]
Hi,
Ok understood, i make it work now. Very good :)
Thanks for this code!

2015-05-24 15:32 GMT+02:00 Osman Nuri Okumuş <notifications@github.com>:

**Comment by skiokko** [comment]
schiocco.com

Off Grid Adventures ( https://schiocco.com )

*****************************************
Let’s start building something together !
*****************************************

Welcome to Check out all my latest Envato products and get exclusive promotions and insights. Cheers and thanks for reading!

New theme available
-------------------

Codrop is an App Landing Page and One Page multipurpose WordPress Theme based on the Bootstrap 4 Grid System, Themekit and WPTF.

( https://1.envato.market/j6Yn6 )

Lot's of premium themes
-----------------------

Static templates
----------------

Premium plugins
---------------

Secret update ...
-----------------

I'm working on the new version of Support Board! It will be a brand new plugin built from scratch with impressive new features. This update is only for the subscribers of this newsletter.

Schiocco

Mindspace, Whitechapel High St 114 , London ,

Unsubscribe (  https://u12139260.ct.sendgrid.net/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcTEHVQP0WbfYWmOx7-2FeXdWpMvBfXPOvw48q802WWyTiuGGQJKNskfD8e1TKrGk0f4pKI1FznrL4CqqEkb9XlnfUY8xu9-2FaiPxUbytzgIP15ejX-2BAc9em-2BytDTyaEmKySlcJFTAeZCa7qkjZ4iAMDtfv6RDq9cpTXYxjOIp0BNm3O49AaO2e5xKjBqiy1cGcSaA-2BtmjWboAF9aaXZjOSOA26nOMjTfFZS8WDBmRMMBOW1r65Jy5OhUz-2BTxpS4pRbo5IHjXC2xlfgCUJ0F3r-2FX2HlkvO-2FkJPA-2BYvBmOnZMa3UoOdVXVvoPL-2BLMGEZxoapbYgJfJjrqVBqc8LtyXpSrVkfOpxLECxxTHFOELxDJtcvWNvN4u5caoEdbJ-2FNU4z2pl-2B22mKKk2iPjfbKDmAuGh79OiV9rJzdvou-2FOGhsuKIo4OmTwq3VVk9VZn3MWk-2FEOrhjNYQZOLh3VGDhegQAhxwaRILl-2FppRyRJw9KEV62D5ripdUzUNbhs47-2Bm1b6o5yS09X6gq9wyZLncx21z-2BI6KA6hcc5HnkQE1UcSeee74hGHhHWI3KAsn3OyKCjDZ0sUzrKEmU-2Fdy0UiK9ji6ux4IohYtJzSHpyvVFLJ4IxotE74PtHNrZDcxoVxBxcSrSlyfnsTaJjowpLlVQzJxNNrNMV6f2LMlnyZxlT-2BTuPpREb  )

© 2019 Schiocco. Visit schiocco.com ( https://schiocco.com ) to view all products.
