### ISSUE TITLE
Arrow toggle is not working 

### ISSUE THREAD

**Issue by chamara-fg** [onokumus/metisMenu#50]
span fa arrow not showing 
![image](https://cloud.githubusercontent.com/assets/8773942/7881569/084ac2ae-0622-11e5-862f-39c840510956.png)

**Comment by chamara-fg** [comment]
and  + icon in third level menu navigation

**Comment by onokumus** [comment]
@chamara-fg 
Add class **metismenu** to unordered list
```html
<ul class="metismenu" id="menu">

</ul>
```

**Comment by chamara-fg** [comment]
I Add the Class to UL is not working
 
![image](https://cloud.githubusercontent.com/assets/8773942/7888705/1d54e2b6-0658-11e5-95da-64cbbcad8898.png)

**Comment by chamara-fg** [comment]
![image](https://cloud.githubusercontent.com/assets/8773942/7889139/3d162e04-065b-11e5-8f23-237d383619c6.png)
same issue in "test/index.html"

**Comment by chamara-fg** [comment]
ThaX for Supporting & Fast Response....

**Comment by onokumus** [comment]
@chamara-fg 
**metismenu** class require for version 2.0.2

**Comment by sundua** [comment]
/*
 * metismenu - v1.1.3
 * Easy menu jQuery plugin for Twitter Bootstrap 3
   * Made by Osman Nuri Okumus
  */

I am using third level menu & when I click the  menu is closing . I want only 3rd level menu to remain expanded. I am using it with sb admin bootstrap. I do not know what other details to give.
