### ISSUE TITLE
Minimum jquery version for using metis menu.

### ISSUE THREAD

**Issue by gursimransingh** [onokumus/metisMenu#52]
Will the metis menu work with jquery 1..3.1.Earlier i was using version 2.1.1 and it was working properly.I have to use version 1.3.1 because my organization has strict restriction to use this version.Please help me with this scenario.

**Comment by onokumus** [comment]
@gursimransingh 
I'm sorry. MetisMenu uses jQuery [on](http://api.jquery.com/on/) method. You can use minimum jQuery 1.7 version.

**Comment by xicath** [comment]
i use jQuery v1.8.3, its not work

**Comment by onokumus** [comment]
@gursimransingh @xicath 
see https://jsfiddle.net/46o1vxL7/

**Comment by xicath** [comment]
ok tq, that work nicely
used it in drupal 7, i will try debug it
tq

**Comment by xicath** [comment]
it seem its because it canoot use jquery shortcut in drupal7
so i change :
$(function() {
    $('#side-menu').metisMenu();
});
to :
jQuery( document ).ready (function() {
   jQuery("#side-menu").metisMenu();
});
in sb-admin-2.js
i use sbadmin2 theme for drupal7
it work nicely now, Tq

**Comment by onokumus** [comment]
http://jsfiddle.net/et7rwypb/embedded/
