### ISSUE TITLE
Bootstrap in depedency 

### ISSUE THREAD

**Issue by codeyash** [onokumus/metisMenu#53]
I'm using it with [inventive ui](https://github.com/speedovation/Inventive) so I don't need bootstrap in bower components though it still download that.

Its possible to use your product without bootstrap so you can include general version and bootstrap version. 

There should not be dependency in package itself when it can easily be replaced with generic.

This way you can reach all audiences not specific ones.

**Comment by onokumus** [comment]
@codeyash 
Which version do you use?

https://github.com/onokumus/metisMenu/blob/master/bower.json#L32

**Comment by codeyash** [comment]
my bad. Yea it was old version. Thanks for reply.
