### ISSUE TITLE
metisMenu as a drop down rather than a sidebar

### ISSUE THREAD

**Issue by LordLiverpool** [onokumus/metisMenu#60]
Hello

I would like MetisMenu to work as a dropdown menu item from a navbar rather than a sidebar.

I can get a normal navbar with a dropdown to work:

http://michaelruddock.co.uk/02navdropbar.php

But when I add metisMenu to a page the dropdown stops working:

http://michaelruddock.co.uk/metis/index.html

If I try to add metisMenu to the navbar as an item the whole navbar becomes messed up

Any ideas?

Thanks.

**Comment by onokumus** [comment]
@LordLiverpool 
Clean duplicate scripts and css files.

**Comment by LordLiverpool** [comment]
Hello onokumus

Thank you for replying. I appreciate your help.

I removed the duplicate js and css files and it fixed the problem of the drop down menu not working, thank you!

I've managed to embed metismenu onto the navbar as a menu item.

However when I click on a menu item from metisMenu it closes.
When I click again on metisMenu the menu item I clicked is expanded.
How do I stop metisMenu from closing like this?

Thank very much

**Comment by LordLiverpool** [comment]
Would stopPropagation work? 

$('.panel-heading a').on('click',function(e){
    if($(this).parents('.panel').children('.panel-collapse').hasClass('in')){
        e.stopPropagation();
    }
});

http://jsfiddle.net/dozoisch/SMT9D/45/ 

I am not sure where to add it?

**Comment by LordLiverpool** [comment]
any luck?

**Comment by onokumus** [comment]
@LordLiverpool 
https://jsfiddle.net/xhuhajy9/1/embedded/result/

**Comment by LordLiverpool** [comment]
Thank you very much, that worked perfectly.

You can now offer metisMenu as either a sidebar menu or a drop down menu.

Cheers :-)

**Comment by onokumus** [comment]
:smile:
