### ISSUE TITLE
Menu items are not clickable?

### ISSUE THREAD

**Issue by LordLiverpool** [onokumus/metisMenu#63]
Hello Onokumus

I was wondering if you could help me with a code change please? 
I recently implemented your metismenu here: http://bit.ly/1hus0IV
The items on the menu that are marked in blue e.g. "Adult Costumes" or "Childrens Costumes" 
I need them to be clickable. They are meant to go to a page on the website.

At the moment the link is somehow turned off. 

How do I change this?

Thanks very much.

Cheers

**Comment by onokumus** [comment]
```css
#menu {
z-index: 11;
}
```

See http://www.w3schools.com/cssref/pr_pos_z-index.asp

**Comment by LordLiverpool** [comment]
It didn't work :-(

If I click Fancy Dress > Adult Costumes and hover on the menu item I can see that the link would go to
http://test1.littlestarparties.ie/fancy-dress-costume-online-shop-ireland 

I can right click and open the link in a new browser tab.

I tried adding your CSS 

#menu {
z-index: 11;
}

I even tried setting the z-index to be 99

it didnt work :-(

BTW the menu id is menu2

so I tried

#menu2 {
z-index: 11;
}

That didn't work either.

What am I missing?

Thank you.

**Comment by onokumus** [comment]
no problem on my browsers (firefox, chromium, opera, etc)
![screen shot 2015-09-01 at 17 49 44](https://cloud.githubusercontent.com/assets/742498/9608297/619f017c-50d6-11e5-9736-9c6778f2c2d2.png)

**Comment by LordLiverpool** [comment]
Yes thats right! :-)

I want to be able to click "Adult Costumes" and go to 

http://test1.littlestarparties.ie/fancy-dress-costume-online-shop-ireland

I don't know how???

**Comment by onokumus** [comment]
```javascript
$('#menu').metisMenu({doubleTapToGo: true });
```

**Comment by LordLiverpool** [comment]
Hey!!! 

That worked :-) :-) :-) 

Thank you very much onokumus you're a star!!!!

**Comment by onokumus** [comment]
Not me!, give a star to metisMenu, can't see you on the list stargazers! 
https://github.com/onokumus/metisMenu/stargazers

**Comment by LordLiverpool** [comment]
Done! :-)

https://github.com/onokumus/metisMenu/stargazers
