### ISSUE TITLE
expand all submenus

### ISSUE THREAD

**Issue by Fredyy90** [onokumus/metismenu#68]
Is there a simple way to expand all submenus?

**Comment by onokumus** [comment]
https://github.com/onokumus/metisMenu#usage

**Comment by salvadoresc** [comment]
i dont see on that link how to expand a submenu.

**Comment by onokumus** [comment]
Add `active` class to `li` element(s) with submenus

**Comment by salvadoresc** [comment]
thanks, it worked removing the class collpase  

$('#leftMenu .collapse').removeClass( "collapse" );

**Comment by mhidalgop** [comment]
Hi, in my case I want to expand a submenu by code. I'm adding `active` class to `li`, but the submenu continues collapsed.
