### ISSUE TITLE
Narrow display requires 2 clicks to open menu

### ISSUE THREAD

**Issue by joetcochran** [onokumus/metisMenu#71]
I purchased the "Nifty" theme from wrapbootstrap (live demo here: http://wrapbootstrap.com/preview/WB0048JF7). I contacted them for support on this issue and they explained the issue is in metisMenu.

Steps to reproduce: 
1) Shrink width of browser window down to approx. 300px to simulate a phone viewport. Should be small enough so the hamburger menu becomes styled as white on a dark background (pic1.png)
![pic1](https://cloud.githubusercontent.com/assets/12942481/10849678/2f6bac5a-7ef8-11e5-9f67-c6a85cdb7332.PNG)

2) Click the hamburger icon once. It does nothing. Only on the second click will it actually expand the menu. All subsequent clicks toggle the menu appropriately.

**Comment by onokumus** [comment]
@joetcochran 

This is not an issue of metisMenu plugin. It is about this code in nifty.min.js :

nifty.document.on("nifty.ready",function(){var t=n(".mainnav-toggle");t.length&&t.on("click",function(e){e.preventDefault(),n.niftyNav(t.hasClass("push")?"pushToggle":t.hasClass("slide")?"slideToggle":t.hasClass("reveal")?"revealToggle":"colExpToggle")});

**Comment by joetcochran** [comment]
Confirmed - this issue can be closed. Sorry for the inconvenience.

**Comment by joetcochran** [comment]
Thanks for helping me narrow this down - I've implemented a fix in the nifty.js template. You should be advised that they were sending people your way for this issue however, in case it comes up in the future. Joe [Fantastic plugin, by the way!]
