### ISSUE TITLE
MetisMenu does not work on Firefox in Mac OS X

### ISSUE THREAD

**Issue by menshinobi** [onokumus/metismenu#74]
On a Firefox browser and MetisMenu does not work on Mac OS X. Menu item does not expand on click.

**Comment by softelos** [comment]
I have Mac OS X and the menu is working fine with me in both Chrome and Firefox. Does it work for you in Chrome? This is to discard any issues from your side.

**Comment by vorbe** [comment]
Can confirm that it's working fine with firefox 45.0 and OSX 10.11.4
