### ISSUE TITLE
React + MetisMenu don't work together properly

### ISSUE THREAD

**Issue by alpertuna** [onokumus/metismenu#92]
Hello,
I'm using [React](https://facebook.github.io/react/) and after React's render, I apply MetisMenu.
If React doesn't render again to update DOM, there is no problem. However, if React renders document more than once, MetisMenu's onClick references get broken so menu not working.
But actual problem is that applying MetisMenu after every render does not solve the problem because after first applying MetisMenu, it doesn't let second time. I notice that MetisMenu uses `jQuery.data()` and `mm` data field to keep plugin values. And to solve the problem, I used this;

``` javascript
$('#menu_container').data('mm',false).metisMenu();
```

I placed above code to execute after every render of React, and problem solved. But it's not confortable that's why I like to note that.

**Comment by onokumus** [comment]
@alpertuna 
Sorunu bir de türkçe olarak onokumus@gmail.com adresine yazar mısın?

**Comment by achapela** [comment]
hi @alpertuna , 
Was it possible to correct this problem?
I tried placing your solution on componentWillUpdate but it keeps doing the same thing. Very anoying. 

Thanks.

**Comment by alpertuna** [comment]
Hi @achapela,
Can you show me the part, how metismenu get involved to your react application, so that I can help you.
Proper correction seems not possible because this metismenu works with dom which initialed at first time, and react renders new dom, so metismenus references are got broken. That's why you should clear metismenu data and initial it for each render.

**Comment by achapela** [comment]
@alpertuna 
componentWillUpdate(nextProps, nextState) {
	$('#side-menu').data('mm').metisMenu();
}
componentDidMount() {
	$('#side-menu').metisMenu();
}

Everything stops working when I click on the "#" links. Could It be react-router is messing things up? It shouldn't be pushing for a new render when that happens. Or should it? I'm using browserHistory.

**Comment by alpertuna** [comment]
Hmm, you used `componentWillUpdate` but you should use `componentDidUpdate` because willUpdate one works before render. It should work after this fix.
By the way, yes it should't render again if you don't change state, it is another case. Nonetheless apply this solution, it should do the job.

**Comment by achapela** [comment]
Did not work. Just stops working.
How did you resolve the "in" and "active" classes in the ul and li elements?
I think my problem is there because I'm resolving with the router.isActive, but my implementation seems to be buggy.

**Comment by alpertuna** [comment]
@achapela 
I looked over my old project for you. I achieved this avoiding render again and for this, I prepared menu part as an external bundle library to make it work independently. However it is not a proper usage. For my new projects I created new menu library just for react recently, you may want to look over it [alpertuna/react-metismenu](https://github.com/alpertuna/react-metismenu)
