### ISSUE TITLE
With Bootstrap 3.3.6 collapse script. `Uncaught TypeError: Cannot read property 'height' of undefined`

### ISSUE THREAD

**Issue by kntmrkm** [onokumus/metisMenu#94]
- * metismenu - v2.5.0

Hi I'm using with bootstrap.

When BS collapse script fired. I got below error.

`Uncaught TypeError: Cannot read property 'height' of undefined`

I remove metisMenu.js temporary.
The error disappeared.

thanks.

**Comment by jondavis0787** [comment]
I have mine working on bootstrap 3.3.6

**Comment by kntmrkm** [comment]
@jondavis0787 
OK. I seems to depend on my env.

I'll check other situation. thanks.

**Comment by stodolos** [comment]
If you upgrade to metismenu - v2.5.2, then the problems disappears 👍
