### ISSUE TITLE
doesn't work for bower

### ISSUE THREAD

**Issue by Rafaelgfirmino** [onokumus/metisMenu#99]
Hi , the command '$ bower install  metismenu '  specified in README.MD it does not work.

The correct is  "$ bower install **metisMenu**"  - using lowerCamelCase.

Thanks!

**Comment by onokumus** [comment]
Thanks @Rafaelgfirmino 
https://github.com/onokumus/metisMenu/commit/73a8abb9a3aa65cd6cbf67ba191bea6f21534778
